---

version: '3'
services: 
  jackd: 
    build: jackd
    volumes: 
      - jackdsock:/dev/shm/:rw
      - /dev/snd:/dev/snd
    ulimits:
      rtprio: 99
    cap_add:
      - SYS_NICE

  jacktrip: 
    build: .
    depends_on: 
      - jackd
    ports: 
      - 4464:4464
    volumes: 
      - jackdsock:/dev/shm/:rw
      - /dev/snd:/dev/snd
    ulimits:
      rtprio: 99
    cap_add:
      - SYS_NICE


volumes: 
  jackdsock: 
