name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jacktrip:$(date +%s)
      
    - name: Build the Docker image
      run: docker build . --file jackd/Dockerfile --tag jackd:$(date +%s)
